Make NumPy available:

In [ ]:
import numpy as np

## Exercise 07.1 (indexing and timing)

Create two very long NumPy arrays `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for vectors of different lengths (use a very long vector for 
the timing). The values of the array entries are not important for this test. Use `%time` to report the time.

*Hint:* To loop over an array using indices, try a construction like:

In [ ]:
x = np.ones(10)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


#### (1) Add two vectors using built-in addition operator:

In [ ]:
x = np.random.rand(10000)
y = np.random.rand(len(x))

%time z = x + y
print (z)

CPU times: user 85 µs, sys: 9 µs, total: 94 µs
Wall time: 101 µs
[0.82805617 0.81003689 1.2062115  ... 0.73880605 1.28487297 1.6120419 ]


#### (2) Add two vectors using own implementation:

In [ ]:
!pip -q install numba 
import numba

def compute_w(x,y):
    w = np.zeros(len(x))
    for i in range(len(x)):
        w[i] = x[i] + y[i]
    return w

@numba.jit
def compute_w_jit(x,y):
    w = np.zeros(len(x))
    for i in range(len(x)):
        w[i] = x[i] + y[i]
    return w

%time w = compute_w(x,y)
compute_w_jit(x,y)
%time w = compute_w_jit(x,y)

CPU times: user 6.44 ms, sys: 0 ns, total: 6.44 ms
Wall time: 6.45 ms
CPU times: user 36 µs, sys: 0 ns, total: 36 µs
Wall time: 39.8 µs


### Optional extension: just-in-time (JIT) compilation

You will see a large difference in the time required between your NumPy and 'plain' Python implementations. This is due to Python being an *interpreted* language as opposed to a *compiled* language. A way to speed up plain Python implementions is to convert the interpreted Python code into compiled code. A tool for doing this is [Numba](https://numba.pydata.org/).

Below is an example using Numba and JIT to accelerate a computation:

In [1]:
!pip -q install numba 
import numba
import math

def compute_sine_native(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z

@numba.jit
def compute_sine_jit(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z
    
x = np.ones(10000000)
%time z = compute_sine_native(x)
compute_sine_jit(x)
%time z = compute_sine_jit(x)

NameError: ignored

**Task:** Test if Numba can be used to accelerate your implementation that uses indexing to sum two arrays, and by how much.

In [ ]:
@numba.jit
def compute_w_jit(x,y):
    w = np.zeros(len(x))
    for i in range(len(x)):
        w[i] = x[i] + y[i]
    return w

compute_w_jit(x,y)
%time w = compute_w_jit(x,y)
print (w)

CPU times: user 36.2 ms, sys: 997 µs, total: 37.2 ms
Wall time: 37 ms
[ 1.47820629  1.56130407  1.79268066 ... 83.79781221 83.24624184
 83.24392949]


## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as percentages, sorted from 
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
   computation, e.g. `max = scores.max()`.  
   
   Design your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
   computation of the min, max and mean. 
   
   *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores 
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [ ]:
def to_percentage_and_sort(scores):
    pscores = scores / 60 * 100
    sort_pscores = np.sort(pscores)
    return sort_pscores

def statistics(scores, exclude=False):
    if exclude == False:
        return {"min": scores.min(), "max": scores.max(), "mean": scores.mean()}
    else: 
        scores = np.sort(scores)
        sliced_scores = scores[1:-1]
        return {"min": sliced_scores.min(), "max": sliced_scores.max(), "mean": sliced_scores.mean()}

In [ ]:
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
assert np.isclose(to_percentage_and_sort(scores), [ 13.0, 40.0, 58.33333333,  70.0, 96.66666667]).all()

s0 = statistics(scores)
assert round(s0["min"] - 7.8, 10) == 0.0
assert round(s0["mean"] - 33.36, 10) == 0.0
assert round(s0["max"] - 58.0, 10) == 0.0

s1 = statistics(scores, True)
assert round(s1["min"] - 24.0, 10) == 0.0
assert round(s1["mean"] - 33.666666666666666667, 10) == 0.0
assert round(s1["max"] - 42.0, 10) == 0.0

## Exercise 07.3 (slicing)

For the two-dimensional array

In [ ]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing for the below operations, printing the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.



#### 1. Extract the third column as a 1D array

In [ ]:
A_3column = np.zeros(len(A))
for i in range(len(A)):
    A_3column[i] = A[i][2]
print(A_3column)

A_3column = A[:,2]
print(A_3column)

[  -2.43   54.7     3.64 -113.2 ]
[  -2.43   54.7     3.64 -113.2 ]


#### 2. Extract the first two rows as a 2D sub-array

In [ ]:
A_2row = A[0:2]
print(A_2row)

[[ 4.    7.   -2.43 67.1 ]
 [-4.   64.   54.7  -3.33]]


#### 3.  Extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [ ]:
A_2block = [[A[-2][-2], A[-2][-1]], [A[-1][-2], A[-1][-1]]]
print(A_2block)

A_2block = A[-2:,-2:]
print(A_2block)

[[3.64, 4.11], [-113.2, 323.22]]
[[   3.64    4.11]
 [-113.2   323.22]]


#### 4. Sum the last column

In [ ]:
A_lastcolumn = A[:, -1]
sum = np.sum(A_lastcolumn)
print(sum)

391.1


#### Compute transpose

Compute the transpose of `A` (search online to find the function/syntax to do this).

In [ ]:
A_transpose = A.transpose()
print(A_transpose)

[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]


## Exercise 07.4 (optional extension)

In a previous exercise you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).

In [ ]:
from scipy import optimize

def my_f(x):
    return x**3 - 6*x**2 + 4*x + 12

# Native function method  
def compute_root(f, x0, x1, tol, max_it):
    "Compute roots of a function using bisection"
    if f(x0)*f(x1) > 0:
        print("no root between x0 and x1.")
    else:
        x_mid = (x0 + x1) / 2
        f_mid = f(x_mid)
        it = 0
        
        while abs(f_mid) > tol and it <= max_it:
            it += 1
            if f(x0)*f(x_mid) < 0:
                x1 = x_mid
            else:
                x0 = x_mid
            x_mid = (x0 + x1) / 2
            f_mid = f(x_mid)
        
        return x_mid, f_mid, it

%time native_root = compute_root(my_f, x0=3, x1=6, tol=1.0e-6, max_it=1000)

# Scipy Optimize
%time scipy_root = optimize.bisect(my_f, 3, 6)



CPU times: user 45 µs, sys: 4 µs, total: 49 µs
Wall time: 51.7 µs
CPU times: user 39 µs, sys: 0 ns, total: 39 µs
Wall time: 41.2 µs
